#!/usr/bin/env bash
set -euo pipefail

# Generate manifest with checksums for all Go source files
# This lets users verify GitHub CDN has the latest version

echo "=== Generating source manifest ==="

MANIFEST_FILE="SOURCE_MANIFEST.txt"

cat > "$MANIFEST_FILE" <<EOF
# Source File Manifest
#
# Generated by: ./update-manifest.sh
#
# Use this to verify GitHub's CDN has the latest version:
# Compare these checksums with what you see in the raw files on GitHub

EOF

# Checksum all Go source files
echo "## Go Source Files" >> "$MANIFEST_FILE"
echo "" >> "$MANIFEST_FILE"

# .claude/ is pruned because git worktrees live under .claude/worktrees/, and
# each one holds a complete second copy of every .go file in the repo. Sweeping
# those in adds paths that do not exist in the published tarball, so bootstrap
# verification fails for users -- and it changes the manifest hash they are
# asked to eyeball, for reasons invisible from the repo. Whether the manifest
# grows depends on whether a worktree happens to exist when this runs, which is
# exactly the kind of nondeterminism a checksum manifest must not have.
find . -name "*.go" -not -path "./vendor/*" -not -path "./.git/*" -not -path "./.claude/*" | sort | while read -r file; do
    hash=$(shasum -a 256 "$file" | awk '{print $1}')
    echo "$hash  $file" >> "$MANIFEST_FILE"
done

echo "" >> "$MANIFEST_FILE"
echo "## Critical Shell Scripts" >> "$MANIFEST_FILE"
echo "" >> "$MANIFEST_FILE"

# Bootstrap installer (entry point)
hash=$(shasum -a 256 lib/bootstrap-installer.sh | awk '{print $1}')
echo "$hash  lib/bootstrap-installer.sh" >> "$MANIFEST_FILE"

# Cleanup script (prepare for fresh install)
hash=$(shasum -a 256 lib/clean-install.sh | awk '{print $1}')
echo "$hash  lib/clean-install.sh" >> "$MANIFEST_FILE"

# Verification script (diagnostic tool)
hash=$(shasum -a 256 lib/verify-guix-install.sh | awk '{print $1}')
echo "$hash  lib/verify-guix-install.sh" >> "$MANIFEST_FILE"

# Recovery script (installation recovery tool)
if [ -f lib/recovery-complete-install.sh ]; then
    hash=$(shasum -a 256 lib/recovery-complete-install.sh | awk '{print $1}')
    echo "$hash  lib/recovery-complete-install.sh" >> "$MANIFEST_FILE"
fi

# ISO artifacts fix script (one-time fix for existing installations)
if [ -f lib/fix-iso-artifacts.sh ]; then
    hash=$(shasum -a 256 lib/fix-iso-artifacts.sh | awk '{print $1}')
    echo "$hash  lib/fix-iso-artifacts.sh" >> "$MANIFEST_FILE"
fi

# Comprehensive filesystem recovery script (complete recovery with system rebuild)
if [ -f lib/recover-filesystem-invariants.sh ]; then
    hash=$(shasum -a 256 lib/recover-filesystem-invariants.sh | awk '{print $1}')
    echo "$hash  lib/recover-filesystem-invariants.sh" >> "$MANIFEST_FILE"
fi

# Post-install library
if [ -f lib/postinstall.sh ]; then
    hash=$(shasum -a 256 lib/postinstall.sh | awk '{print $1}')
    echo "$hash  lib/postinstall.sh" >> "$MANIFEST_FILE"
fi

# Shared postinstall library
if [ -f postinstall/lib.sh ]; then
    hash=$(shasum -a 256 postinstall/lib.sh | awk '{print $1}')
    echo "$hash  postinstall/lib.sh" >> "$MANIFEST_FILE"
fi

echo "" >> "$MANIFEST_FILE"
echo "## Guile Library Scripts" >> "$MANIFEST_FILE"
echo "" >> "$MANIFEST_FILE"

# Guile config helper (critical for postinstall)
if [ -f lib/guile-config-helper.scm ]; then
    hash=$(shasum -a 256 lib/guile-config-helper.scm | awk '{print $1}')
    echo "$hash  lib/guile-config-helper.scm" >> "$MANIFEST_FILE"
fi

# Bootstrap postinstall script
if [ -f lib/bootstrap-postinstall.scm ]; then
    hash=$(shasum -a 256 lib/bootstrap-postinstall.scm | awk '{print $1}')
    echo "$hash  lib/bootstrap-postinstall.scm" >> "$MANIFEST_FILE"
fi

# Network fix script (Guile)
if [ -f lib/fix-network.scm ]; then
    hash=$(shasum -a 256 lib/fix-network.scm | awk '{print $1}')
    echo "$hash  lib/fix-network.scm" >> "$MANIFEST_FILE"
fi

# Finish installation script (Guile)
if [ -f lib/finish-installation.scm ]; then
    hash=$(shasum -a 256 lib/finish-installation.scm | awk '{print $1}')
    echo "$hash  lib/finish-installation.scm" >> "$MANIFEST_FILE"
fi

# Postinstall library (Guile)
if [ -f postinstall/lib.scm ]; then
    hash=$(shasum -a 256 postinstall/lib.scm | awk '{print $1}')
    echo "$hash  postinstall/lib.scm" >> "$MANIFEST_FILE"
fi

echo "" >> "$MANIFEST_FILE"
echo "## Diagnostic Scripts" >> "$MANIFEST_FILE"
echo "" >> "$MANIFEST_FILE"

# Pre-deployment validation script
if [ -f lib/validate-before-deploy.sh ]; then
    hash=$(shasum -a 256 lib/validate-before-deploy.sh | awk '{print $1}')
    echo "$hash  lib/validate-before-deploy.sh" >> "$MANIFEST_FILE"
fi

# Diagnose guix build script
if [ -f diagnose-guix-build.sh ]; then
    hash=$(shasum -a 256 diagnose-guix-build.sh | awk '{print $1}')
    echo "$hash  diagnose-guix-build.sh" >> "$MANIFEST_FILE"
fi

# Investigate kernel location script
if [ -f investigate-kernel-location.sh ]; then
    hash=$(shasum -a 256 investigate-kernel-location.sh | awk '{print $1}')
    echo "$hash  investigate-kernel-location.sh" >> "$MANIFEST_FILE"
fi

echo "" >> "$MANIFEST_FILE"
echo "## Tools" >> "$MANIFEST_FILE"
echo "" >> "$MANIFEST_FILE"

# Log serving helper (Guile)
if [ -f tools/serve-logs.scm ]; then
    hash=$(shasum -a 256 tools/serve-logs.scm | awk '{print $1}')
    echo "$hash  tools/serve-logs.scm" >> "$MANIFEST_FILE"
fi

echo "" >> "$MANIFEST_FILE"
echo "## Post-Install Customization Scripts" >> "$MANIFEST_FILE"
echo "" >> "$MANIFEST_FILE"

# Platform-specific customization tools
for customize in */postinstall/customize; do
    if [ -f "$customize" ]; then
        hash=$(shasum -a 256 "$customize" | awk '{print $1}')
        echo "$hash  $customize" >> "$MANIFEST_FILE"
    fi
done

# Platform-specific customization tools (Guile Scheme)
for customize_scm in */postinstall/customize.scm; do
    if [ -f "$customize_scm" ]; then
        hash=$(shasum -a 256 "$customize_scm" | awk '{print $1}')
        echo "$hash  $customize_scm" >> "$MANIFEST_FILE"
    fi
done

# Postinstall recipe scripts (Guile Scheme)
find postinstall/recipes -name "*.scm" -type f | sort | while read -r file; do
    hash=$(shasum -a 256 "$file" | awk '{print $1}')
    echo "$hash  $file" >> "$MANIFEST_FILE"
done

echo "" >> "$MANIFEST_FILE"
echo "## Oracle Cloud Scripts and Tests" >> "$MANIFEST_FILE"
echo "" >> "$MANIFEST_FILE"

find oracle -name "*.scm" -type f | sort | while read -r file; do
    hash=$(shasum -a 256 "$file" | awk '{print $1}')
    echo "$hash  $file" >> "$MANIFEST_FILE"
done

find oracle/scripts -name "*.sh" -type f | sort | while read -r file; do
    hash=$(shasum -a 256 "$file" | awk '{print $1}')
    echo "$hash  $file" >> "$MANIFEST_FILE"
done

echo ""
echo "Manifest written to $MANIFEST_FILE"
echo ""

# Calculate and display the manifest checksum itself
MANIFEST_HASH=$(shasum -a 256 "$MANIFEST_FILE" | awk '{print $1}')

# Convert hash to human-readable words when the local Go toolchain works.
# The words are a convenience; the SHA256 manifest and its hash remain the
# authority, so an incomplete/missing Go installation must not make generation
# fail after the manifest was successfully written.
MANIFEST_WORDS=$(go run cmd/hash-to-words/main.go "$MANIFEST_HASH" 2>/dev/null || true)

echo "================================================================"
echo "MANIFEST CHECKSUM (verify this on Guix ISO before running):"
echo ""
echo "  Hash: $MANIFEST_HASH"
if [ -n "$MANIFEST_WORDS" ]; then
    echo "  Words: $MANIFEST_WORDS"

    # Extract first 3 and last 3 words
    WORD_ARRAY=($MANIFEST_WORDS)
    FIRST_THREE="${WORD_ARRAY[0]} ${WORD_ARRAY[1]} ${WORD_ARRAY[2]}"
    LAST_IDX=$((${#WORD_ARRAY[@]} - 1))
    LAST_THREE="${WORD_ARRAY[$((LAST_IDX - 2))]} ${WORD_ARRAY[$((LAST_IDX - 1))]} ${WORD_ARRAY[$LAST_IDX]}"
    echo "  Quick: $FIRST_THREE ... $LAST_THREE"
fi
echo ""
echo "On Guix ISO, verify with:"
echo "  curl -fsSL https://raw.githubusercontent.com/durantschoon/guix-platform-install/main/SOURCE_MANIFEST.txt | shasum -a 256"
if [ -n "$MANIFEST_WORDS" ]; then
    echo ""
    echo "Or verify with words (easier to read aloud):"
    echo "  curl -fsSL https://raw.githubusercontent.com/durantschoon/guix-platform-install/main/SOURCE_MANIFEST.txt | shasum -a 256 | awk '{print \$1}' | ./hash-to-words"
fi
echo ""
echo "If checksums match, GitHub CDN has the latest version."
echo "================================================================"
echo ""
echo "File checksums:"
cat "$MANIFEST_FILE"
