[advisories]
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
ignore = [
    # ed25519-dalek (1.x branch) has an advisory RUSTSEC-2022-0093, but we use 2.x
    "RUSTSEC-2022-0093"
]

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Zlib",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "OpenSSL",
    "CC0-1.0",
    "BSL-1.0",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
